{% set name = "tiptop" %}
{% set version = "0.0.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiptop-{{ version }}.tar.gz
  sha256: 2958e5c05c702225813c48e9861899956f4242cc03807c7a87f9390626966aa3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tiptop = tiptop._app:run

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - distro
    - importlib-metadata
    - psutil
    - py-cpuinfo
    - python >=3.7
    - rich
    - textual

test:
  imports:
    - tiptop
  commands:
    - pip check
    - tiptop -h
  requires:
    - pip

about:
  home: https://github.com/nschloe/tiptop
  summary: A command-line system monitoring tool in the spirit of top.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
